### PR TITLE
[pre-commit] Added pyupgrade utility for py3.6

### PR DESCRIPTION
**Pull request by DjLegolas**
Added the `pyupgrade` utility to `pre-commit` configuration file, for manual run only.
In addition, I ran it on all the files.

### CODE REVIEW

**Comment by DjLegolas** [comment]
Seem as the tests are failing because of the web server is shutting down for some reason...
On my local WSL env, all tests pass.
@cas-- have any ideas?

**Comment by bwitt** [comment]
the error is a timeout I think?

`2021-12-28T21:40:02.0048871Z twisted.internet.defer.TimeoutError: <deluge.tests.test_web_api.WebAPITestCase testMethod=test_get_torrent_files> (tearDown) still running at 120.0 secs`

https://pipelines.actions.githubusercontent.com/YgbzgFTkKkp7wLSFjWmcyRCipfPOCOYpfCXbhTzFBaRFbsMvHV/_apis/pipelines/1/runs/264/signedlogcontent/4?urlExpires=2021-12-29T18%3A54%3A52.6882850Z&urlSigningMethod=HMACV1&urlSignature=8QBxRhqjk3xkrffKjjENC04H6pCqMNPdsRcNePLozQI%3D

**Comment by bwitt** [comment]
also suggest changing `python_requires='>=3.5',` to 3.6
https://github.com/deluge-torrent/deluge/blob/897955f0a164349d3191c778cfcb37ee9bff9daf/setup.py#L593

**Comment by DjLegolas** [comment]
> the error is a timeout I think?
> 
> `2021-12-28T21:40:02.0048871Z twisted.internet.defer.TimeoutError: <deluge.tests.test_web_api.WebAPITestCase testMethod=test_get_torrent_files> (tearDown) still running at 120.0 secs`
> 
> https://pipelines.actions.githubusercontent.com/YgbzgFTkKkp7wLSFjWmcyRCipfPOCOYpfCXbhTzFBaRFbsMvHV/_apis/pipelines/1/runs/264/signedlogcontent/4?urlExpires=2021-12-29T18%3A54%3A52.6882850Z&urlSigningMethod=HMACV1&urlSignature=8QBxRhqjk3xkrffKjjENC04H6pCqMNPdsRcNePLozQI%3D

I think it's because the server exited unexpectedly but the test still waits for it and fails on timeout.

**Comment by cas--** [comment]
Looks like the latest docs failure is due to `sphinxcontrib-spelling` issue. Pinning to `sphinxcontrib-spelling==7.3.0` in docs requirements.txt should resolve it.

**Pull request closed without merging**
