### PR TITLE
Updated the Norwegian translation considerably

### PR DESCRIPTION
**Pull request by DandelionSprout**
Significant portions of the GUI lacked Norwegian translations, so I decided to improve it a fair bit.

I'll continue working on the translation once Deluge v2 gets an installable Windows version.

### CODE REVIEW

**Comment by cas--** [comment]
Please use the Launchpad translation site: https://deluge.readthedocs.io/en/latest/contributing/translations.html

**Comment by DandelionSprout** [comment]
I would have done so, but there wasn't a Norwegian language option there for some reason.

**Comment by cas--** [comment]
Hmm okay, let me look into that

**Comment by cas--** [comment]
I updated the translations to reuse 1.3 so Norwegian is available: https://translations.launchpad.net/deluge/2.0/+pots/deluge/nb/+translate

**Pull request closed without merging**
