### PR TITLE
[#3501] Fix gdk.pixbuf crash loading tracker icons

### PR DESCRIPTION
**Pull request by doadin**

### CODE REVIEW

**Review by cas-- — COMMENTED** [review]
A few things, this only applies to Windows so must be a check for that and should not be converting to png in this function, if anything in TrackerIcons code.

**Comment by DjLegolas** [comment]
I think this should be a last resort solution...
Try to use the image, abd if we fail, convert.
Unless we cannot catch the error/exception at all.

**Comment by doadin** [comment]
@cas--  go for it.

**Comment by cas--** [comment]
@DjLegolas Unfortunately this is hard crash in GdkPixbuf

**Pull request closed without merging**
