### PR TITLE
bugfix for peers tab failing to set flag location request.country returns bytes not a string

### PR DESCRIPTION
**Pull request by thelamer**
Running into this downstream: 

https://github.com/linuxserver/docker-deluge/issues/66

Tested locally and flags work for me with this change.

### CODE REVIEW

**Comment by cas--** [comment]
Thanks merged!  a34543100c5

**Comment by thelamer** [comment]
@cas-- is there a disconnect with your downstream debs  or does stuff from this repo not go into those ? 
The latest release we pulled in does not have this change but you merged and tagged it properly here. 

Grab deb:
```
mkdir delugetmp
cd delugetmp
wget http://ppa.launchpad.net/deluge-team/stable/ubuntu/pool/main/d/deluge/deluge-web_2.0.3-1~201906082034~ubuntu18.04.1_all.deb
ar x deluge-web_2.0.3-1~201906082034~ubuntu18.04.1_all.deb
tar xf data.tar.xz 
```
output: 
```
thelamer@drop ~/delugetmp $ cat usr/lib/python3/dist-packages/deluge/ui/web/server.py |grep country
        request.country = path
        path = ('ui', 'data', 'pixmaps', 'flags', request.country.lower() + '.png')
```

**Comment by cas--** [comment]
Thanks!! I forgot that it needs to pull the git repo before hitting build button! I'll fix it just now

**Comment by cas--** [comment]
I assume the version is still showing as 2.0.2 for `deluge-web --version`?

**Comment by downtowns** [comment]
the linuxserver/deluge docker container I pulled down earlier today reports:
deluge-web 2.0.3-1-201906082034-ubuntu18.04.1
libtorrent: 1.1.5.0
Python: 3.6.8
OS: Linux 4.9.125-linuxkit

Which aligns with "latest" listed at https://hub.docker.com/r/linuxserver/deluge/tags

**Comment by cas--** [comment]
A new version `2.0.3-2~201906121747` has been published

**Comment by thelamer** [comment]
flags
All good now thanks!

**Pull request closed without merging**
