### PR TITLE
Store width and height of 'Edit trackers' dialog in config file.

### PR DESCRIPTION
**Pull request by Arzie**
See description ;-).

PS: I tried the workaround in http://forum.deluge-torrent.org/viewtopic.php?f=7&t=51737 with about 10 proxies, but unfortunately to no avail.

### CODE REVIEW

**Comment by Arzie** [comment]
*ping* any comments on this?

**Comment by cas--** [comment]
No comment means it looks fine :) It's not completely forgotten about I shall get around to merging it.

**Comment by cas--** [comment]
Merged: [d4535c61648d2702]

**Comment by Arzie** [comment]
Merci for the merge :-).

**Pull request closed without merging**
