### PR TITLE
convert pygtk to pygi

### PR DESCRIPTION
**Pull request by doadin**

### CODE REVIEW

**Comment by doadin** [comment]
oops def not ready for a pull

**Comment by bendikro** [comment]
Hi

Thanks for your efforts on trying to contribute, but as you noticed it was not at all ready for being pulled.

For bigger issues like this it's a good idea to create a ticket first so it can be discussed and followed there.

You should also take a look at the [development page](http://dev.deluge-torrent.org/wiki/Development), specifically the pages [Provide Patches or Pull Requests](http://dev.deluge-torrent.org/wiki/Contributing/PullRequests) and [Unit testing](http://dev.deluge-torrent.org/wiki/Development/Testing)

If you believe a branch is ready for merging, you should ensure that the commit history is fairly clean. You can clean it up by rebasing and squashing commits that do not need to be separate.

Also, I recommend creating an account on https://travis-ci.org and connect your github account to automatically run the tests when you push commits. You'll then be able to see the build errors on your branch before you create a pull request. You can run the tox commands performed by travis locally as described [here](http://dev.deluge-torrent.org/wiki/Development/Testing#Tox).

As for the work on moving to pygi, are you aware  of the pygi-convert.sh script?
I ran the script on develop and made some changes necessary to make it run on [bendikro/deluge/tree/develop-pygi2](https://github.com/bendikro/deluge/commits/develop-pygi2). There are still more to change required, but it's a start.

**Comment by doadin** [comment]
yea the pull request was a mistake, thats why i said "oops def not ready for a pull". And yes the pygi-convert.sh is the first commit you see on here. The rest are additional errors/warnings i fixed up after. If you would like to contribute feel free to fork my branch and make pull requests and ill merge them and be happy to clean it up to one commit as we get closer to a final product.

**Comment by doadin** [comment]
by the way i just merged your "Working on pygi" into my develop-pygi branch in my fork.

**Comment by doadin** [comment]
I also made a ticket here: http://dev.deluge-torrent.org/ticket/2743

**Pull request closed without merging**
