### PR TITLE
[Core] Ensure magnet name passed to lt in string

### PR DESCRIPTION
**Pull request by bendikro**

### CODE REVIEW

**Comment by Duvian** [comment]
thnx
Date: Sun, 3 Apr 2016 17:06:38 -0700

**Comment by cas--** [comment]
Merged: [bebc414136f37645a58795d0cf6ddcee77425152]

**Comment by cas--** [comment]
Just thought, should this also apply to 1.3-stable?

**Comment by bendikro** [comment]
Yeah, same issue there

**Comment by cas--** [comment]
Could you create another PR for that, thanks

**Pull request closed without merging**
