### PR TITLE
lossless compression of images saved 457KB

### PR DESCRIPTION
**Pull request by Fish2**
Save Bandwidth and speed up website load time but lossless completion of all images.

doing this saved 457KB docent sound like much but why not

### CODE REVIEW

**Comment by cas--** [comment]
Thanks for this but how can this be scripted? 

Also this is failing the tests because you compressed a comparison png.

**Comment by Fish2** [comment]
I used AdvPNG and PNGOUT so you could probably use that but would have to add it to the build requirements which would then make the build bigger.

I have added a fix for the comparison test

**Comment by cas--** [comment]
It is a dev tool not for inclusion with build. I see that `advpng` is available for Ubuntu with `apt install advancecomp` so we can use that. The current scripts under `deluge/scripts` can be extended to run over the pngs and compress them.

**Comment by Fish2** [comment]
that sounds good to me

**Comment by diogocp** [comment]
advpng is not very good. pngcrush is also available in Ubuntu and will probably give you much better results. See https://css-ig.net/png-test-corpus for a comparison of various tools.

Converting the GIFs to PNG should also help.

**Comment by cas--** [comment]
pngs have been compressed with zopflipng: fe42fb2c31d87b013

**Pull request closed without merging**
