### PR TITLE
[AutoAdd] Fixed error dialog not being shown on error

### PR DESCRIPTION
**Pull request by DjLegolas**
This issue might be the cause [3069](https://dev.deluge-torrent.org/ticket/3069).

### CODE REVIEW

**Review by cas-- — CHANGES_REQUESTED** [review]
We can just replace with `message` attribute since `exception_msg` was removed with changes to RPC protocol: 9b812a4eec6205b98

**Comment by DjLegolas** [comment]
> We can just replace with `message` attribute since `exception_msg` was removed with changes to RPC protocol: [9b812a4](https://github.com/deluge-torrent/deluge/commit/9b812a4eec6205b98d9d5c12c14f82611832217a)

I saw it in [another place](https://github.com/deluge-torrent/deluge/blob/44dcbee5f43b454994b3a6173bdd27802120e707/deluge/ui/console/cmdline/commands/connect.py#L61) so I copied the behavior in case it still exists.
Change that too?

**Comment by cas--** [comment]
Yep change there too :+1:

**Comment by cas--** [comment]
That looks fine, do you mind updating the commit message to mention the reason for change and reference commit id 9b812a4

**Review by cas-- — APPROVED** [review]

**Comment by DjLegolas** [comment]
> That looks fine, do you mind updating the commit message to mention the reason for change and reference commit id [9b812a4](https://github.com/deluge-torrent/deluge/commit/9b812a4eec6205b98d9d5c12c14f82611832217a)

Hope it is good enough 😄

**Comment by cas--** [comment]
That was exactly what was needed :+1: 

Remember to add a reference to the Trac ticket in commit messages too, something like this:

image

I automatically add the pr close line to simplify workflow so don't worry about that.

**Pull request closed without merging**
