### PR TITLE
Update Mac Packaging

### PR DESCRIPTION
**Pull request by doadin**
Currently will produce a atrifact zip that contains similar structure to windows install.
If you extract that zip inside are binaries and those binaries run fine.

Currently trying to work out how to make a ".app".

### CODE REVIEW

**Comment by cas--** [comment]
We already have a solution for [creating an .app](https://github.com/deluge-torrent/deluge/pull/273) so let's not make using pyinstaller a priority

**Comment by doadin** [comment]
@cas--  Well, I figured out the issue and this build process works better than on windows so, idk. Up to you what you want. Its here if you want it or I can just close this. However its working now with little to no workarounds or anything like that. Other than some normal spec file things it just deletes requirments.txt from the dist. That other option is not merged and uses a different build system I think Its simpler to use pyinstaller for both, It can even use one single pyinstaller spec file if you want.(only seperate currently for testing)

**Comment by cas--** [comment]
That's good to know, I just wanted to concentrate on one platform for now

**Comment by doadin** [comment]
@cas-- I am going to go ahead and close this since I'm taking a break. Currently it builds and everything runs fine on 10.15 from the dist folder however the .app it makes I could not get to run not sure if its just user error or not I don't develop on mac very much so really not sure. I updated with some improvements learned from the windows builds. The only thing not working is the deluge exe is commented out even though it would run. The problem was it makes the .app fail to build I believe due to having the same name as the dist folder, If it was done on a case sensitive FS would probably be ok.

**Pull request closed without merging**
