### PR TITLE
Refactor/gtk builder plugins

### PR DESCRIPTION
**Pull request by DjLegolas**
Ticket  [#3002](http://dev.deluge-torrent.org/ticket/3002) - Convert Deluge Plugins to GtkBuilder

### CODE REVIEW

**Comment by cas--** [comment]
Thanks for this, I'll need to look at why the tests are failing.

**Comment by DjLegolas** [comment]
I tested it on my system (configured as close as possible the one Travis's initializes) and all tests passed.

In addition, I started testing the AutoAdd changes, but there is an issue with the Label plugin in which the label selected is not being added to the torrent.

**Comment by cas--** [comment]
So I have fixed and merged these changes. Thanks again :+1: 

Quick note that the change from ComboBoxEntry to ComboBox also needed a change to the method that was being used to set the item from `set_text_column` to `set_entry_text_column`.

The was another unrelated autoadd-label issue to do with changes to the core api, which I have fixed: 26720ca4c2

**Comment by doadin** [comment]
Not 100% sure it was after this change but, after updating from ~ 7b87a93862bae5bcb53d4134a111a308ec36f9e8 to 26720ca4c2e96b1c4c2df145a3642e57d870652b the notifications plugin enables but has no tab label in the plugins list section in the Preferences window. After clicking Prefferences > Plugins and enabling notifications a tab is made but is blank. Clicking on the blank tab does bring up the options for notifications though.

**Comment by DjLegolas** [comment]
I looked in the code and the reason Notifications behaves like this is due to the way it inserts itself to the list.
Every other plugin just calls to the [`add_page`](https://github.com/deluge-torrent/deluge/blob/develop/deluge/ui/gtkui/preferences.py#L194) function.
But Notifications doesn't. It just [adds itself](https://github.com/deluge-torrent/deluge/blob/develop/deluge/plugins/Notifications/deluge/plugins/notifications/gtkui.py#L266) to the list of items directly and does it partially. And, it's easy to fix this. Just need to replace lines 266 to 271 with the line:
```python
component.get('Preferences').add_page(_('Notifications'), self.prefs)
```
Regarding Blocklist... My bad, didn't see this line.
@cas-- Should I fix the error in Bloaklist in a new PR or in this one?

**Pull request closed without merging**
